Tildes y typos arreglados en el post
varango2143/Hyperblog.github.io pull request #1
Opened 2020-06-10 17:49 UTC by varango2143

No debimos pasar éste error a master.

2020-06-10 19:44 UTC, AnitaPruebas requested changes
En vez de usar tildes directas, usa entidades HTML.

2020-06-13 17:55 UTC, AnitaPruebas commented
Cambios hechos, por favor hazme el merge.

2020-06-13 18:02 UTC, varango2143 commented
Cambios hechos, por favor hazme el merge.

2020-06-13 18:19 UTC, AnitaPruebas approved these changes
Excelente, eso era!

2020-06-13 18:28 UTC, merged